// LingoLeap content database
// Each language has three decks: vocabulary, phrases, grammar
// pron = simple phonetic pronunciation guide

const LANGUAGES = {
  spanish: {
    name: "Spanish",
    flag: "🇪🇸",
    color: "#E8B339",
    vocabulary: [
      { id: "es-v1", term: "el agua", translation: "water", pron: "el AH-gwah" },
      { id: "es-v2", term: "la casa", translation: "house", pron: "lah KAH-sah" },
      { id: "es-v3", term: "el amigo", translation: "friend (m)", pron: "el ah-MEE-go" },
      { id: "es-v4", term: "comer", translation: "to eat", pron: "ko-MEHR" },
      { id: "es-v5", term: "el libro", translation: "book", pron: "el LEE-bro" },
      { id: "es-v6", term: "feliz", translation: "happy", pron: "feh-LEES" },
      { id: "es-v7", term: "el tiempo", translation: "time / weather", pron: "el tee-EM-po" },
      { id: "es-v8", term: "trabajar", translation: "to work", pron: "trah-bah-HAR" },
      { id: "es-v9", term: "la ciudad", translation: "city", pron: "lah see-oo-DAHD" },
      { id: "es-v10", term: "el perro", translation: "dog", pron: "el PEH-rro" },
    ],
    phrases: [
      { id: "es-p1", term: "¿Cómo estás?", translation: "How are you?", pron: "KOH-mo es-TAHS" },
      { id: "es-p2", term: "Mucho gusto", translation: "Nice to meet you", pron: "MOO-cho GOOS-toh" },
      { id: "es-p3", term: "¿Dónde está el baño?", translation: "Where is the bathroom?", pron: "DON-deh es-TAH el BAH-nyo" },
      { id: "es-p4", term: "No entiendo", translation: "I don't understand", pron: "no en-tee-EN-doh" },
      { id: "es-p5", term: "¿Cuánto cuesta?", translation: "How much does it cost?", pron: "KWAN-toh KWES-tah" },
      { id: "es-p6", term: "Buen provecho", translation: "Enjoy your meal", pron: "bwen pro-VEH-cho" },
      { id: "es-p7", term: "Hasta luego", translation: "See you later", pron: "AHS-tah loo-EH-go" },
      { id: "es-p8", term: "Tengo hambre", translation: "I am hungry", pron: "TEN-go AHM-breh" },
    ],
    grammar: [
      { id: "es-g1", title: "Ser vs Estar", explanation: "Spanish has two verbs for 'to be'. Use ser for permanent traits, estar for temporary states.", example: "Soy alto. / Estoy cansado.", exampleTranslation: "I am tall. / I am tired." },
      { id: "es-g2", title: "Gendered nouns", explanation: "Every noun is masculine or feminine, shown by el/la and usually the ending -o or -a.", example: "el libro, la mesa", exampleTranslation: "the book, the table" },
      { id: "es-g3", title: "Plurals", explanation: "Add -s after a vowel, -es after a consonant.", example: "el amigo → los amigos", exampleTranslation: "the friend → the friends" },
      { id: "es-g4", title: "Present tense -ar verbs", explanation: "Drop -ar and add endings: -o, -as, -a, -amos, -áis, -an.", example: "hablar → hablo, hablas, habla", exampleTranslation: "to speak → I speak, you speak, he/she speaks" },
      { id: "es-g5", title: "Question marks", explanation: "Spanish questions open with an inverted question mark ¿ and close with a normal one ?.", example: "¿Hablas español?", exampleTranslation: "Do you speak Spanish?" },
    ],
  },

  french: {
    name: "French",
    flag: "🇫🇷",
    color: "#5C7AEA",
    vocabulary: [
      { id: "fr-v1", term: "l'eau", translation: "water", pron: "loh" },
      { id: "fr-v2", term: "la maison", translation: "house", pron: "lah meh-ZOHN" },
      { id: "fr-v3", term: "l'ami", translation: "friend (m)", pron: "lah-MEE" },
      { id: "fr-v4", term: "manger", translation: "to eat", pron: "mahn-ZHAY" },
      { id: "fr-v5", term: "le livre", translation: "book", pron: "luh LEEV-ruh" },
      { id: "fr-v6", term: "heureux", translation: "happy", pron: "uh-RUH" },
      { id: "fr-v7", term: "le temps", translation: "time / weather", pron: "luh TAHN" },
      { id: "fr-v8", term: "travailler", translation: "to work", pron: "trah-vah-YAY" },
      { id: "fr-v9", term: "la ville", translation: "city", pron: "lah VEEL" },
      { id: "fr-v10", term: "le chien", translation: "dog", pron: "luh shee-EHN" },
    ],
    phrases: [
      { id: "fr-p1", term: "Comment ça va?", translation: "How are you?", pron: "koh-mahn sah VAH" },
      { id: "fr-p2", term: "Enchanté", translation: "Nice to meet you", pron: "ahn-shahn-TAY" },
      { id: "fr-p3", term: "Où sont les toilettes?", translation: "Where is the bathroom?", pron: "oo sohn lay twah-LET" },
      { id: "fr-p4", term: "Je ne comprends pas", translation: "I don't understand", pron: "zhuh nuh kohm-prahn PAH" },
      { id: "fr-p5", term: "Combien ça coûte?", translation: "How much does it cost?", pron: "kohm-bee-EHN sah KOOT" },
      { id: "fr-p6", term: "Bon appétit", translation: "Enjoy your meal", pron: "bohn ah-pay-TEE" },
      { id: "fr-p7", term: "À tout à l'heure", translation: "See you later", pron: "ah toot ah LUHR" },
      { id: "fr-p8", term: "J'ai faim", translation: "I am hungry", pron: "zhay FAHN" },
    ],
    grammar: [
      { id: "fr-g1", title: "Gendered nouns", explanation: "Every noun is masculine or feminine, marked by le/la (l' before a vowel).", example: "le livre, la maison", exampleTranslation: "the book, the house" },
      { id: "fr-g2", title: "Plurals", explanation: "Most nouns add -s, but it is usually silent when spoken.", example: "le chien → les chiens", exampleTranslation: "the dog → the dogs" },
      { id: "fr-g3", title: "-er verbs", explanation: "Drop -er and add endings: -e, -es, -e, -ons, -ez, -ent.", example: "parler → je parle, tu parles", exampleTranslation: "to speak → I speak, you speak" },
      { id: "fr-g4", title: "Negation", explanation: "Wrap the verb with ne ... pas to make it negative.", example: "Je ne sais pas.", exampleTranslation: "I don't know." },
      { id: "fr-g5", title: "Liaison", explanation: "A normally silent final consonant is pronounced when the next word starts with a vowel.", example: "les amis", exampleTranslation: "(sounds like) lay-zah-MEE" },
    ],
  },

  japanese: {
    name: "Japanese",
    flag: "🇯🇵",
    color: "#D64550",
    vocabulary: [
      { id: "ja-v1", term: "水 (mizu)", translation: "water", pron: "MEE-zoo" },
      { id: "ja-v2", term: "家 (ie)", translation: "house", pron: "ee-EH" },
      { id: "ja-v3", term: "友達 (tomodachi)", translation: "friend", pron: "toh-moh-DAH-chee" },
      { id: "ja-v4", term: "食べる (taberu)", translation: "to eat", pron: "tah-BEH-roo" },
      { id: "ja-v5", term: "本 (hon)", translation: "book", pron: "HOHN" },
      { id: "ja-v6", term: "嬉しい (ureshii)", translation: "happy", pron: "oo-REH-shee" },
      { id: "ja-v7", term: "時間 (jikan)", translation: "time", pron: "JEE-kahn" },
      { id: "ja-v8", term: "働く (hataraku)", translation: "to work", pron: "hah-tah-RAH-koo" },
      { id: "ja-v9", term: "街 (machi)", translation: "city / town", pron: "MAH-chee" },
      { id: "ja-v10", term: "犬 (inu)", translation: "dog", pron: "EE-noo" },
    ],
    phrases: [
      { id: "ja-p1", term: "お元気ですか (Ogenki desu ka)", translation: "How are you?", pron: "oh-GEHN-kee dess kah" },
      { id: "ja-p2", term: "はじめまして (Hajimemashite)", translation: "Nice to meet you", pron: "hah-jee-meh-mah-SHTEH" },
      { id: "ja-p3", term: "トイレはどこですか (Toire wa doko desu ka)", translation: "Where is the bathroom?", pron: "toy-reh wah doh-koh dess kah" },
      { id: "ja-p4", term: "わかりません (Wakarimasen)", translation: "I don't understand", pron: "wah-kah-ree-mah-SEN" },
      { id: "ja-p5", term: "いくらですか (Ikura desu ka)", translation: "How much does it cost?", pron: "ee-koo-rah dess kah" },
      { id: "ja-p6", term: "いただきます (Itadakimasu)", translation: "Said before eating", pron: "ee-tah-dah-kee-mahss" },
      { id: "ja-p7", term: "またね (Mata ne)", translation: "See you later", pron: "mah-tah neh" },
      { id: "ja-p8", term: "お腹が空きました (Onaka ga sukimashita)", translation: "I am hungry", pron: "oh-nah-kah gah soo-kee-mah-shtah" },
    ],
    grammar: [
      { id: "ja-g1", title: "Sentence order", explanation: "Japanese follows Subject-Object-Verb order, the opposite of English.", example: "私はりんごを食べます", exampleTranslation: "I apple eat. (I eat an apple.)" },
      { id: "ja-g2", title: "Particles", explanation: "Small words like は (wa), を (o), and が (ga) mark the role of the word before them.", example: "猫は可愛い", exampleTranslation: "Cat (topic) is cute." },
      { id: "ja-g3", title: "No plurals", explanation: "Nouns don't change for singular or plural; context tells you which is meant.", example: "本 (hon)", exampleTranslation: "book / books" },
      { id: "ja-g4", title: "Politeness levels", explanation: "Verbs change form depending on how formal you want to sound, e.g. -masu for polite speech.", example: "食べる → 食べます", exampleTranslation: "to eat (plain) → to eat (polite)" },
      { id: "ja-g5", title: "Two scripts for vocabulary", explanation: "Hiragana spells native words and grammar; katakana spells foreign loanwords.", example: "コーヒー (kohi)", exampleTranslation: "coffee (loanword, written in katakana)" },
    ],
  },

  german: {
    name: "German",
    flag: "🇩🇪",
    color: "#6B8F71",
    vocabulary: [
      { id: "de-v1", term: "das Wasser", translation: "water", pron: "dahs VAH-sser" },
      { id: "de-v2", term: "das Haus", translation: "house", pron: "dahs HOWS" },
      { id: "de-v3", term: "der Freund", translation: "friend (m)", pron: "dehr FROYND" },
      { id: "de-v4", term: "essen", translation: "to eat", pron: "ESS-en" },
      { id: "de-v5", term: "das Buch", translation: "book", pron: "dahs BOOKH" },
      { id: "de-v6", term: "glücklich", translation: "happy", pron: "GLUHK-lish" },
      { id: "de-v7", term: "die Zeit", translation: "time", pron: "dee TSYTE" },
      { id: "de-v8", term: "arbeiten", translation: "to work", pron: "AR-by-ten" },
      { id: "de-v9", term: "die Stadt", translation: "city", pron: "dee SHTAHT" },
      { id: "de-v10", term: "der Hund", translation: "dog", pron: "dehr HOOND" },
    ],
    phrases: [
      { id: "de-p1", term: "Wie geht es dir?", translation: "How are you?", pron: "vee gayt es deer" },
      { id: "de-p2", term: "Freut mich", translation: "Nice to meet you", pron: "froyt mish" },
      { id: "de-p3", term: "Wo ist die Toilette?", translation: "Where is the bathroom?", pron: "voh ist dee toy-LET-uh" },
      { id: "de-p4", term: "Ich verstehe nicht", translation: "I don't understand", pron: "ish fer-SHTAY-uh nisht" },
      { id: "de-p5", term: "Was kostet das?", translation: "How much does it cost?", pron: "vahs KOS-tet dahs" },
      { id: "de-p6", term: "Guten Appetit", translation: "Enjoy your meal", pron: "GOO-ten ah-peh-TEET" },
      { id: "de-p7", term: "Bis später", translation: "See you later", pron: "bis SHPAY-ter" },
      { id: "de-p8", term: "Ich habe Hunger", translation: "I am hungry", pron: "ish HAH-buh HOONG-er" },
    ],
    grammar: [
      { id: "de-g1", title: "Three genders", explanation: "Nouns are masculine, feminine, or neuter, shown by der, die, or das.", example: "der Hund, die Stadt, das Haus", exampleTranslation: "the dog, the city, the house" },
      { id: "de-g2", title: "Capitalized nouns", explanation: "Every noun is capitalized, no matter where it appears in the sentence.", example: "Ich lese ein Buch.", exampleTranslation: "I am reading a book." },
      { id: "de-g3", title: "Verb-second word order", explanation: "The conjugated verb is always the second element in a main clause.", example: "Heute arbeite ich.", exampleTranslation: "Today work I. (Today I work.)" },
      { id: "de-g4", title: "Cases", explanation: "Nouns and articles change form (cases) depending on their grammatical role: subject, object, etc.", example: "der Hund → den Hund", exampleTranslation: "the dog (subject) → the dog (object)" },
      { id: "de-g5", title: "Compound words", explanation: "German builds long words by stringing nouns together.", example: "Handschuh", exampleTranslation: "hand + shoe = glove" },
    ],
  },
};
